steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/macro-outpost-429513-r8/cloud-run-app','--build-arg=PROJECT_ID=macro-outpost-429513-r8', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/macro-outpost-429513-r8/cloud-run-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '--image', 'gcr.io/macro-outpost-429513-r8/cloud-run-app', '--region', 'us-central1','--allow-unauthenticated','--platform','managed']
 

options:
  logging: CLOUD_LOGGING_ONLY 
